{% set name = "latexcodec" %}
{% set version = "2.0.0" %}
{% set sha256 = "2b69cf97231d16db95e2ee5a30a9a33a1ebfa76b0d9c5085e9c72f8a5210c08f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mcmtroffaes/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - latexcodec

about:
  home: https://github.com/mcmtroffaes/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'Lexer and codec to work with LaTeX code in Python.'
  doc_url: http://latexcodec.readthedocs.io/
  dev_url:  https://github.com/mcmtroffaes/{{ name }}

extra:
  recipe-maintainers:
    - scopatz
