travis:
  secure:
    BINSTAR_TOKEN: AAnONFP847ToUgtVknncTeL43Ke8atvbtNiHKceCqh8Yk25VMSk1NEZ/1cQwLrxChB9vPdd5O1JsqddVWU1SC28+XhA2P0A63s8MdYJac20a24hJ90IXS6NHhKPnnrToz3rh7DZRmQ4Rjy0oaOthQE9z6bwJCAPl9sCe4hyzQZrWijgpPk8+f8WEicCzgpRKXCF3CIAJNTa5WFycLMjkHJpe/GDUy6Cnj/DwRAfigzhrMfQs0/FkG2HRneaKxxIgvhETj+EvSFLr/g5h9hatr4IKsZkuxf3y1IU6a53xROj01qcbMnQVxVJ4RP86MMxTF5QjAKKAjcjmrCG7Q2Qm7lAOpvSdP1pzMHd5FyDXqeh64wyS3i6rcJBxJzOkaXPQJdNlZ4yQKzQdPjqsVtGQOUvRjIc5Z0y5lD2DItSXo0EDvin94yBwvM+CxvkObxcc1v5z5vjhLIzCXVSOWnvply5NEHGRVH5ISzTDTLfzD13RB+nteu6lKMUWCv5VYu0pmb4MyNo2V7zO+bhe4VVR5ltclSSnVA6KskSY6D4FD2OviJykCcTVj7tpZa3xGZ7ITYHTvzZmZp7ZnvPMkY3ZW5DxUxQ/VNRifx1Xn/Ts0/t5noPapf0U1k1CBDKxDDGRwiVUUiKQHp4xAKkcuwy3C5KALjsrqWWOFX4vn97Hk2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
