travis:
  secure:
    BINSTAR_TOKEN: nLfU5YiRiSpZ8IG0Nn+3nWGBGvrI1sAjyHKOly+yv05KrFEdcMGMZZ/0V057P1yZjNeMOM4CNbFYrrPeozK7q+nfGsBVQFKwbp/srCCjFS5ordJE1xjtcRT8VqXEvvM6aqOVwwvXXyn5IgLs7d4xnHuxSQMUC7E9NFdUf7bnnKiuWHNoz6yjew/rFLkoUNZeITfA6FWc5NNP/Qz9qzWGUwFTs2hWLVGfnF94Eke/qWDeGdg2nPspOEeItGdd6bCU8BIHTiGlbdWMr81GyeXly36bcG7otess+rkuBEgnai8lgSBdyGBNTw/5buVp+l8R+Xqw7QKz9C2kE04ZdygtGTbq/9qq8xDdLvYiYsE+mgW7sEizn0NxInodv/XN7zpCUQsWBJRcLI+90NpABq4pbqUxXGkblxYM2368SszCiEZd7grwLSVMVteJ4p1pQpEd0j6EPYCTXGsJ3DAy0BEP2CLgeSaIteUqympi+PaLvm1ypuxA6ZltLr2zXL/av/d58pvG7I9iVxULHTjT2YlSiPeK+bUdT/fipJDWo29nE/k9wMsBGabP7iZlhdSwadmnkJ9p5pbR3nfaPMZntiW+XyfixkqARWyNYFv320giEstq+2HHol9uj/Uc7lPj88eJB2fp+ndLLdX2WTS0Qi0Lta2e0VRE48Bd8++H7wFJmmg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
