travis:
  secure:
    BINSTAR_TOKEN: Ycp086ispMCzOIaB457jfF5YIH1pGOCviu4kqLaRqTt2PHXbj8v+KpWYkmprxFbYpf62NM+atyWZpdvBDMTxrGooBi5LLNI9KVsj/7x9tQBG97RXJtTv907WRtTCXAUMpY7PZcU3oRz+5nIzfbAUIBmGq2T3SfTruNL5G+v2OjsYlDT5aU9qKNkESCOmDmg6i+WqDF+kFHzkKthnfS6WbypNEHNXrZoG6M6FOv4qyQ/RtLCkiIHP8fEsTk0erwcIClUcny4Yg3gi0CXwlrUohM+0q+YySsw8oZkQdys4AqlSRb36tci/aWs9wyONcZf6+3hlWc3SlJRtqCGbx7LqHgGdGaeX7JvROkxdztph3oyyPAQDfssTyxNRNLJpiF7CraY7IlcJ5RD6LOWUNHzrDLizpGHYtRqM4ZyJH8LxrAoa4NBg6jI1ogcsoa5ekdvo+xRQimoj2+prneYYuELveFlAYB0AnTSfpyRd4XRbITaV47giARCQ5RS9YJGjiN+LSYv8KRJMjPK8+vdhlNXfWMsEIMhofPrDh/crOhGkOBH76c7n7b2Q4z63Vd1X8lI1kUGYF8clcqhWFSY5GJbjYc+ssHIvSelsewOpeRa94JZ26TYFqZTwEyQc8VXrnAHcaGJe7WDFe/IclEkI6OE0QjrMBKHLIVXOYf77NzxzMC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
