travis:
  secure:
    BINSTAR_TOKEN: gc/flVAGpfxFgOyFqEQPLdOIG1hGB5cvHzYUXIrA2dHHqvhUGLzQ533cTo8dRop+xzOZj44dvxuNW62HdMVhbpPMu+PlMOuAN82tqr8pwJD4b1wDYbLO9mUd++mwt1H9JQBErKieB9P12uV+MXMEEbaDqpGjBIB5uf15gxQtA4xvCDe0++IIRoBdyq+8PLGjoUkpxrObnDlz2Zh2X7QMhV/6YcJZT47EEWat+EIUJ2hgRS+mJN99XOpNC8cZsGPvv1nkZXeMrow782i5rUaIWcWo2B4ayQ/+ORyD+MxCsCyk9ThOwLAoy2luMecwz085crBMb5/FGKSFHsVZqNLB+tCjr1/K6RagTpMh3QizkMIBZ0i2eTwvTP6zZfXsKQCexdpGspmufzAO3HMypToNevp3+C9HO4UKTwbAn8qK2ouI85PeDSHMz9e4W7CgWTdKsW5o1xVe7YcBnYdaKncugCIyg1JHZLHEfIR1qMvAoklh3rXkPlhFsKEqezSjS84oySDOVtButGsMieyaGIyX9IA9uJTMZpSBmuvxN679xGfaeQ4jrHgfaJ3dXYpKClm8YeIIPYaCQQFtT00zzk0NoxwfdxFOirNB2bbjnsUqCLOrfNCS4fMDLjWUSp8bEVrZKErsPg3NT02GgSeYSqDrFdoAHYJmEp4TKtjC6EOucJc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
